apiVersion: v1
kind: Pod
metadata:
  name: rsync-client
  labels:
    demo.io/name: rsync-client
    demo.io/app: rsync-client
    demo.io/role: rsync-client
spec:
  containers:
  - name: rsync-client
    image: ghcr.io/k8s-volume-copy/rsync-client
    command:
    - rsync
    args:
    - "-rv"
    - "rsync://$(RSYNC_USERNAME)@rsync-daemon:873/data"
    - "/data"
    env:
    - name: RSYNC_USERNAME
      value: user
    - name: RSYNC_PASSWORD
      value: pass
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    emptyDir: {}
  restartPolicy: Never
