name: build and push image

on:
  push:
    branches:
    - main
  release:
    types:
    - created

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set image tag for release
      if: github.event_name == 'release' && github.event.action == 'created'
      run: |
        REF="${GITHUB_REF#refs/*/v}"
        echo "IMAGE_TAG=${REF}" >> $GITHUB_ENV
        echo "LATEST_TAG=latest" >> $GITHUB_ENV

    - name: Login to ghcr
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build & Push Image
      run: make push-image
